#!/usr/bin/env python3
# This file is part of rosgpt package for ROS1.

import json
import requests

def send_text_command(text_command):
    """
    Sends a text command to the ROSGPT system and receives a response from the ChatGPT language model.
    Supports both English and Chinese commands.
    """
    data = {'text_command': text_command}

    try:
        # 發送 HTTP POST 請求
        response = requests.post('http://localhost:5000/rosgpt', data=data, timeout=10)

        # 檢查回應狀態碼
        if response.status_code == 200:
            response_str = response.content.decode('utf-8')
            try:
                # 嘗試解析回應內容為 JSON
                response_dict = json.loads(response_str)
                print("\nGPT Response:", response_dict.get('text', 'No text response found'))
                print("\nParsed JSON:", response_dict.get('json', 'No JSON response found'))
            except json.JSONDecodeError:
                # JSON 解析失敗時打印原始內容
                print('[JSONDecodeError] 無效或空的 JSON 字串：', response_str)
            except Exception as e:
                print('[Exception] 解析回應時發生未知錯誤：', str(e))
        else:
            # 非 200 狀態碼時打印伺服器回應
            print(f"[伺服器錯誤] 狀態碼: {response.status_code}, 回應內容: {response.text}")
    except requests.exceptions.Timeout:
        print("[錯誤] 請求超時，請檢查伺服器是否正在運行或請求是否過慢。")
    except requests.exceptions.RequestException as e:
        print(f"[連接錯誤] 無法訪問 ROSGPT 伺服器: {e}")

if __name__ == '__main__':
    """
    This script allows the user to input a text command, which is sent to the ROSGPT system
    using the send_text_command() function. The response generated by ChatGPT is printed
    to the console.
    """
    while True:
        print("請輸入中文或英文指令 (例如: '前進 3 公尺，然後順時針旋轉 90 度'):")
        text_command = input("Enter a text command: ")
        if text_command.strip().lower() == "exit":
            print("已退出程式。")
            break
        send_text_command(text_command)
